-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        rounding = 14,
        rounding_power = 3.8,
    },
    general = {
        border_size = 0,
        gaps_in = 1,
        gaps_out = 4,
        layout = "dwindle",
    },
})

-- Keybinds
hl.unbind("SUPER + C")
hl.bind("SUPER + C", hl.dsp.exec_cmd("google-chrome-stable"))
hl.unbind("SUPER + D")
hl.bind("SUPER + D", hl.dsp.exec_cmd("dolphin"))
hl.unbind("SUPER + S")
hl.bind("SUPER + S", hl.dsp.exec_cmd("prime-run /home/avi/.sklauncher/SKlauncher-4.0.48-x86_64.AppImage"))
hl.unbind("SHIFT + CTRL + Q")
hl.bind("SHIFT + CTRL + Q", hl.dsp.exec_cmd("missioncenter"))
hl.unbind("SUPER + A")
hl.bind("SUPER + A", hl.dsp.exec_cmd("hypremoji"))
